spring:
  application:
    name: 3_1_12

  datasource:
    url: jdbc:mariadb://localhost:3306/spring_boot_upgrade_test
    username: root
    password: mypass
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8085